-- Ray/cone query test (Issues #30/#29). Client-initiated: left click fires a ray
-- check, right click fires a cone check, both along the camera's current forward
-- direction. Synchronous request/response - no events generated by the query itself.
function onMouseDown(entity, event)
    local button = event:getMouseButton()
    local origin = entity:getPosition()
    local dir = entity:getForward()

    if button == 0 then -- LMB
        game:showDebugRay(origin.x, origin.y, origin.z, dir.x, dir.y, dir.z, 100)
        local n = game:rayQuery(origin.x, origin.y, origin.z, dir.x, dir.y, dir.z, 100, false)
        game:log("[Ray] hits=" .. n)
        for i = 0, n - 1 do
            local ent = game:getRayHitEntity(i)
            local d = game:getRayHitDistance(i)
            local p = game:getRayHitPosition(i)
            game:log("  [" .. i .. "] " .. ent:getName() .. " dist=" .. string.format("%.2f", d)
                .. " pos=(" .. string.format("%.2f,%.2f,%.2f", p.x, p.y, p.z) .. ")")
        end
    elseif button == 1 then -- RMB
        game:showDebugCone(origin.x, origin.y, origin.z, dir.x, dir.y, dir.z, 20, 100)
        local n = game:coneQuery(origin.x, origin.y, origin.z, dir.x, dir.y, dir.z, 20, 100, true)
        game:log("[Cone] hits=" .. n)
        for i = 0, n - 1 do
            local ent = game:getConeHitEntity(i)
            local d = game:getConeHitDistance(i)
            game:log("  [" .. i .. "] " .. ent:getName() .. " dist=" .. string.format("%.2f", d))
        end
    end
end
