target_sources(ECX PRIVATE
    ADS_TextureSet.cpp
    ADS_TextureSet.h
    BloomChain.cpp
    BloomChain.h
    BufferType.h
    CubeMapBuffer.cpp
    CubeMapBuffer.h
    CubemapManager.cpp
    CubemapManager.h
    CubemapShadowPool.cpp
    CubemapShadowPool.h
    DebugVisualization.h
    ExemptShadowCompositeBuffer.cpp
    ExemptShadowCompositeBuffer.h
    FrameBuffer.cpp
    FrameBuffer.h
    FrameBufferSet.cpp
    FrameBufferSet.h
    FrameBufferType.h
    GBuffer.cpp
    GBuffer.h
    GL_DebugRenderer.cpp
    GL_DebugRenderer.h
    GL_Deferred_Renderer.cpp
    GL_Deferred_Renderer.h
    GL_SkyboxRenderer.cpp
    GL_SkyboxRenderer.h
    HDRLoader.cpp
    HDRLoader.h
    LightData.h
    LightUniformBuffer.cpp
    LightUniformBuffer.h
    MeshManager.cpp
    MeshManager.h
    ObjModel.cpp
    ObjModel.h
    PBR_TextureSet.cpp
    PBR_TextureSet.h
    RenderConfig.h
    Renderer.cpp
    Renderer.h
    Shader.cpp
    Shader.h
    ShaderManager.cpp
    ShaderManager.h
    ShadowAtlas.cpp
    ShadowAtlas.h
    TextureManager.cpp
    TextureManager.h
    TextureSet.cpp
    TextureSet.h
)

add_subdirectory(UI)
